export const ADD_PRODUCT = "ADD_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const FILTER_PRODUCT = "FILTER_PRODUCT";
export const CLEAR_FILTER_PRODUCT = "CLEAR_FILTER_PRODUCT";
